param(
    [string]$TargetDir = "..\Dodian-Client",
    [string]$RuneLiteRepo = "https://github.com/runelite/runelite.git",
    [string]$RuneLiteRef = "master",
    [string]$ManifestUrl = "http://127.0.0.1:4567/client_manifest.json"
)

$ErrorActionPreference = "Stop"

function Write-Step($Message) {
    Write-Host "[dodian-client] $Message"
}

function Ensure-Remote($RepoPath, $RemoteName, $RemoteUrl) {
    $remotes = @(git -C $RepoPath remote)
    if ($remotes -notcontains $RemoteName) {
        git -C $RepoPath remote add $RemoteName $RemoteUrl
    }
}

function Import-RuneliteBase($RepoPath, $RemoteName, $RuneLiteRef, $HasCommit) {
    git -C $RepoPath fetch $RemoteName $RuneLiteRef --depth 1
    if ($HasCommit) {
        $trackedFiles = @(git -C $RepoPath ls-tree --name-only -r HEAD)
        if ($trackedFiles.Count -gt 2) {
            throw "Target repository already has committed files. Refusing to replace it automatically: $RepoPath"
        }
        $backupBranch = "dodian-bootstrap-seed"
        git -C $RepoPath branch $backupBranch HEAD *> $null
        Write-Step "Preserved existing seed commit on branch '$backupBranch'"
    }
    git -C $RepoPath checkout -B main FETCH_HEAD
}

$resolvedTarget = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($TargetDir)
$sourceRemote = "runelite-source"

if (Test-Path $resolvedTarget) {
    if (-not (Test-Path (Join-Path $resolvedTarget ".git"))) {
        throw "Target directory exists but is not a git repository: $resolvedTarget"
    }
    Write-Step "Using existing repository at $resolvedTarget"
    $hasCommit = $true
    git -C $resolvedTarget rev-parse --verify HEAD *> $null
    if ($LASTEXITCODE -ne 0) {
        $hasCommit = $false
    }
    $hasClientSources = (Test-Path (Join-Path $resolvedTarget "runelite-client")) -or
        (Test-Path (Join-Path $resolvedTarget "settings.gradle")) -or
        (Test-Path (Join-Path $resolvedTarget "settings.gradle.kts")) -or
        (Test-Path (Join-Path $resolvedTarget "pom.xml"))
    if (-not $hasClientSources) {
        Write-Step "Repository does not contain client sources; importing RuneLite base while preserving existing remotes"
        Ensure-Remote $resolvedTarget $sourceRemote $RuneLiteRepo
        Import-RuneliteBase $resolvedTarget $sourceRemote $RuneLiteRef $hasCommit
    }
} else {
    Write-Step "Cloning RuneLite base into $resolvedTarget"
    git clone --branch $RuneLiteRef --depth 1 $RuneLiteRepo $resolvedTarget
}

$manifest = $null
try {
    Write-Step "Fetching Alter manifest from $ManifestUrl"
    $manifest = Invoke-RestMethod -Uri $ManifestUrl -Method Get
} catch {
    Write-Warning "Could not fetch the Alter manifest. Start the Alter server and REST service before validating runtime values."
}

$notesPath = Join-Path $resolvedTarget "ALTER_CLIENT_BOOTSTRAP.md"
$revision = if ($manifest -and $manifest.revision) { $manifest.revision } else { "228" }
$loginHost = if ($manifest) { $manifest.endpoints.loginHost } else { "127.0.0.1" }
$loginPort = if ($manifest) { $manifest.endpoints.loginPort } else { "43594" }
$js5Host = if ($manifest) { $manifest.endpoints.js5Host } else { "127.0.0.1" }
$js5Ports = if ($manifest) { ($manifest.endpoints.js5Ports -join ", ") } else { "43594" }
$minimumClientVersion = if ($manifest) { $manifest.client.minimumVersion } else { "0.1.0" }

@"
# Dodian Client Bootstrap

Generated by ``tools/client/bootstrap-alter-client.ps1``.

## Runtime Manifest

- Manifest URL: ``$ManifestUrl``
- Revision: ``$revision``
- Login: ``${loginHost}:${loginPort}``
- JS5: ``${js5Host}`` ports ``${js5Ports}``
- Minimum client version: ``$minimumClientVersion``

## First Patch Targets

1. Add an Alter manifest fetcher during client startup.
2. Replace hardcoded login, world-list, JS5, revision, and RSA values with manifest values.
3. Brand the title, tray icon, config directory, cache directory, and launcher metadata as Dodian.
4. Disable broad Plugin Hub loading by default.
5. Load only curated first-party plugin identifiers from the manifest allowlist.
6. Fail startup with a clear message when manifest revision, cache build id, RSA modulus, or minimum client version is incompatible.

## Development Checklist

- Start the Alter server.
- Open ``http://127.0.0.1:4567/client_manifest.json`` and confirm the manifest is reachable.
- Run the client from this repository with RSProx closed.
- Confirm login reaches Alter directly.
- Confirm the patched cache displays custom map changes.
- Confirm Plugin Hub is not available unless explicitly re-enabled.
"@ | Set-Content -Path $notesPath -Encoding UTF8

Write-Step "Wrote $notesPath"
Write-Step "Bootstrap complete."
